export const nextSkills = [
    "TypeScript",
    "Node.js",
    "Express.js",
    "React Context",
    "Cypress",
    "Unit testing",
    "JS classes",
    "TanStack Query",
    "Python w/ Django or Flask",
];

export const skills = [
    "React",
    "React Hooks",
    "React Router",
    "Redux(Toolkit)",
    "Redux - Saga",
    "Promises, Async / Await",
    "Working with API(fetch, axios)",
    "Error handling",
    "Immutability",
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "JavaScript: ES6 +",
    "CSS Flexbox",
    "CSS Grid",
    "CSS BEM convention",
    "Markdown",
    "Git",
    "NPM",
    "GitHub Pull Requests & Review",
    "Client relations",
    "Multidisciplinary teamwork",
    "Scrum",
    "Trello",
];